# Generated by Django 5.0.4 on 2026-06-29 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('hiring_for', models.CharField(choices=[('self', 'Self'), ('client', 'Client')], default='self', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on-hold', 'On Hold')], default='open', max_length=20)),
                ('resume_upload_link', models.CharField(blank=True, max_length=500)),
                ('assigned_recruiters', models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
