# Generated by Django 5.0.4 on 2026-07-18 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('min_experience', models.PositiveIntegerField(default=0)),
                ('max_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(max_length=150)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], default='medium', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='office', max_length=20)),
                ('job_type', models.CharField(choices=[('permanent', 'Permanent'), ('contractual', 'Contractual')], default='permanent', max_length=20)),
                ('hiring_for', models.CharField(choices=[('self', 'Self'), ('client', 'Client')], default='self', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on-hold', 'On Hold')], default='open', max_length=20)),
                ('target_closing_date', models.DateField(blank=True, null=True)),
                ('notice_period_preference', models.CharField(blank=True, max_length=50)),
                ('skill_criteria', models.DecimalField(decimal_places=2, default=70, max_digits=3, max_length=5)),
                ('resume_upload_link', models.CharField(blank=True, max_length=500)),
                ('assigned_recruiters', models.ManyToManyField(blank=True, limit_choices_to={'role': 'recruiter'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stages', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.job')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='accounts.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
