# Generated by Django 5.0.4 on 2026-07-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resume_upload_link',
        ),
    ]
