# Generated by Django 5.0.4 on 2026-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_resume_upload_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill_criteria',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
