# Generated by Django 5.0.4 on 2026-07-28 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_skill_criteria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'manager'), ('role', 'admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
