# Generated by Django 5.0.4 on 2026-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_hiring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hiring_for',
            field=models.CharField(choices=[('self', 'Self'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
