# Generated by Django 5.0.4 on 2026-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_hiring_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
