# Generated by Django 5.0.4 on 2026-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_description_file_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='team_member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
