# Generated by Django 5.0.4 on 2026-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_team_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('ongoing', 'Ongoing'), ('close', 'Close'), ('hold', 'Hold')], default='open', max_length=20),
        ),
    ]
