# Generated by Django 5.0.4 on 2026-08-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_experience',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_experience',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
