# Generated by Django 5.0.4 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_max_experience_alter_job_min_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='openings',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill_criteria',
            field=models.CharField(blank=True, default='70.0', max_length=50, null=True),
        ),
    ]
