# Generated by Django 5.0.4 on 2026-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_budget_alter_job_openings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
