# Generated by Django 5.0.4 on 2026-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='client_agreements/'),
        ),
    ]
