# Generated by Django 5.0.4 on 2026-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_agreement_document_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agreement_document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
