# Generated by Django 5.0.4 on 2026-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_agreement_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commercial_decided',
            field=models.TextField(blank=True),
        ),
    ]
