# Generated by Django 5.0.4 on 2026-07-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_commercial_decided_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='team_members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
