# Generated by Django 5.0.4 on 2026-08-04 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_access_token_user_google_refresh_token_and_more'),
        ('clients', '0005_client_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberTrackerFormat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_member_id', models.CharField(max_length=255)),
                ('columns', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_formats', to='clients.client')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='accounts.organization')),
            ],
            options={
                'unique_together': {('client', 'team_member_id')},
            },
        ),
    ]
