# Generated by Django 5.0.4 on 2026-08-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_teammembertrackerformat_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembertrackerformat',
            name='header_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammembertrackerformat',
            name='text_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
