# Generated by Django 5.0.4 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_teammembertrackerformat_header_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_period_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='replacement_period_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
