# Generated by Django 5.0.4 on 2026-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_access_token_user_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='microsoft_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='microsoft_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='microsoft_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
