# Generated by Django 5.0.4 on 2026-06-29 09:17

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=200)),
                ('candidate_name', models.CharField(max_length=150)),
                ('current_profile', models.CharField(max_length=200)),
                ('current_company', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=150)),
                ('preferred_location', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('doc', models.DateField(blank=True, null=True)),
                ('current_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('offer_in_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period', models.CharField(max_length=50)),
                ('reason_for_change', models.TextField(blank=True)),
                ('share_date', models.DateField(default=datetime.date.today)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('screening', 'Screening'), ('interview-scheduled', 'Interview Scheduled'), ('sent-to-client', 'Sent To Client'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('on-hold', 'On Hold')], default='screening', max_length=30)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_file_name', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_candidates', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='jobs.stage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('client_feedback', models.TextField(blank=True)),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_submission', to='candidates.candidate')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In Person'), ('telephonic', 'Telephonic')], max_length=20)),
                ('interviewer_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='candidates.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
