# Generated by Django 5.0.4 on 2026-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_duplicate_of_candidate_is_duplicate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='college',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_ctc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='expected_ctc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='offer_in_hand',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='reason_for_change',
        ),
        migrations.AddField(
            model_name='application',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='doc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_in_hand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='reason_for_change',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
