# Generated by Django 5.0.4 on 2026-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
