# Generated by Django 5.0.4 on 2026-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_application_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='manager_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='manager_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resubmit', 'Resubmit')], default='pending', max_length=30),
        ),
    ]
