# Generated by Django 5.0.4 on 2026-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
