# Generated by Django 5.0.4 on 2026-07-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_current_company_and_more'),
        ('candidates', '0005_application_manager_review_notes_and_more'),
    ]

    operations = [
    ]
