# Generated by Django 5.0.4 on 2026-07-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_merge_20260729_1056'),
        ('candidates', '0007_applicationhistory'),
    ]

    operations = [
    ]
