# Generated by Django 5.0.4 on 2026-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hike',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='tracker_custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
