# Generated by Django 5.0.4 on 2026-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_application_hike_application_tracker_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hike',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
