# Generated by Django 5.0.4 on 2026-08-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_current_ctc_candidate_expected_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offer_in_hand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reason_for_change',
            field=models.TextField(blank=True, null=True),
        ),
    ]
