# Generated by Django 5.0.4 on 2026-08-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidate_dob_candidate_offer_in_hand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('no-show', 'No Show'), ('reschedule-requested', 'Reschedule Requested')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='manager_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
