# Generated by Django 5.0.4 on 2026-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_interviewschedule_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
    ]
