# Generated by Django 5.0.4 on 2026-08-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_application_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_ctc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='expected_ctc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_in_hand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='current_ctc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_ctc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='offer_in_hand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
