# Generated by Django 5.0.4 on 2026-08-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_alter_application_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='manager_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
