# Generated by Django 5.0.4 on 2026-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_alter_application_manager_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubmission',
            name='client_rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
