# Generated by Django 5.0.4 on 2026-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_alter_clientsubmission_client_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('screening', 'Screening'), ('interview-scheduled', 'Interview Scheduled'), ('sent-to-client', 'Sent To Client'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('on-hold', 'On Hold'), ('interview-align', 'Interview Align'), ('select', 'Select'), ('offered', 'Offered'), ('joined', 'Joined'), ('backout', 'Backout'), ('duplicate', 'Duplicate')], default='screening', max_length=30),
        ),
    ]
