# Generated by Django 5.0.4 on 2026-09-16 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_microsoft_access_token_and_more'),
        ('candidates', '0017_alter_clientsubmission_client_rating'),
        ('notifications', '0003_notification_from_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField()),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('email_type', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='sent', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidate')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
